name: Video Restoration

on:
  workflow_dispatch:  # lets you run manually from Actions tab
  push:
    paths:
      - '**.py'
      - 'requirements.txt'

jobs:
  restore:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # needed for Real-ESRGAN submodule

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Download sample video
      - name: Download test video
        run: |
          mkdir -p input
          curl -L -o input/sample.mp4 https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4

      # Step 5: Run Preview Mode
      - name: Run Preview
        run: |
          python3 video-restoration-suite/preview.py \
            --input input/sample.mp4 \
            --output output/preview.mp4

      # Step 6: Upload result
      - name: Upload Preview Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-output
          path: output/preview.mp4
