name: Video Processing (Preview or Restore)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Choose processing mode"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - restore

jobs:
  process_video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt || echo "⚠️ Partial dependency install"

      - name: Download test video
        run: |
          mkdir -p input
          curl -L -o input/sample.mp4 https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4

      - name: Run processing
        run: |
          mkdir -p output
          python3 process_video.py \
            --input input/sample.mp4 \
            --output output/result.mp4 \
            --mode ${{ github.event.inputs.mode }} || echo "⚠️ Script exited with warnings"

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: processed-video
          path: output/result.mp4
