name: AI Video Restoration Pipeline

on:
  workflow_dispatch:
    inputs:
      input_url:
        description: "URL of source video"
        required: true
      output_name:
        description: "Output filename"
        default: "restored_4k.mp4"
      processing_mode:
        description: "Processing intensity"
        default: "full"
        type: choice
        options:
          - preview
          - standard
          - full

env:
  MODEL_PATH: "RealESRGAN/weights/RealESRGAN_x4plus.pth"
  TEMP_DIR: "/tmp/video_processing"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      model_ready: ${{ steps.model_check.outputs.exists }}
    steps:
      - name: Check models
        id: model_check
        run: |
          if [ -f "$MODEL_PATH" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

  process:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gpu_enabled: [false]
        include:
          - gpu_enabled: true
            runner: [self-hosted, gpu]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download source
        run: |
          mkdir -p input
          wget "${{ github.event.inputs.input_url }}" -O input/source.mp4
          echo "INPUT_FILE=input/source.mp4" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsm6 libxext6

      - name: Install Python deps
        run: |
          pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu118
          pip install opencv-python basicsr realesrgan tqdm

      - name: Conditional model download
        if: needs.setup.outputs.model_ready == 'false'
        run: |
          mkdir -p RealESRGAN/weights
          wget https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/RealESRGAN_x4plus.pth -O $MODEL_PATH

      - name: Run processing
        run: |
          python process_video.py \
            --input "$INPUT_FILE" \
            --output "${{ github.event.inputs.output_name }}" \
            --temp_dir "$TEMP_DIR" \
            --scale ${{ contains(github.event.inputs.processing_mode, 'full') && '4' || '2' }} \
            --tile_size ${{ matrix.gpu_enabled && '400' || '200' }} \
            --model_path "$MODEL_PATH" \
            ${{ github.event.inputs.processing_mode == 'preview' && '--skip_errors' || '' }}

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: restored-video
          path: |
            ${{ github.event.inputs.output_name }}
            processing_logs.txt

      - name: Cleanup
        if: always()
        run: rm -rf "$TEMP_DIR"
