name: Video Restoration

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - '.github/workflows/restore.yml'

jobs:
  restore:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare input/output folders
        run: |
          mkdir -p input output

      - name: Download test video (if no input provided)
        run: |
          if [ -z "$(ls -A input)" ]; then
            curl -L -o input/sample.mp4 https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4
          fi

      - name: Run Preview Mode
        run: |
          python3 video-restoration-suite/preview.py \
            --input input/sample.mp4 \
            --output output/preview.mp4

      - name: Upload Preview Artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-output
          path: output/preview.mp4
